#!/usr/bin/env python3
"""
Train the unified health risk MLP and export to TFLite.

Synthetic data is generated by the same rule thresholds used in the Kotlin
engines (VitalsRiskMonitor / DehydrationRiskModel / OverexertionModel).
This produces a model that learns to approximate the rule engines while
allowing continuous score output and combined inference in one forward pass.

Usage:
    python train_health_risk.py --out models/
    python train_health_risk.py --out models/ --samples 100000 --epochs 80
"""

import argparse
import os

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
import joblib

from config import (
    HR_RISK_BATCH_SIZE, HR_RISK_EPOCHS, HR_RISK_LR,
    HR_RISK_SYNTHETIC_SAMPLES, RANDOM_SEED,
)
from health_risk_model import HealthRiskMLP


# ── Feature indices ───────────────────────────────────────────────────────────
FEAT_HR    = 0  # heart_rate_bpm
FEAT_SPO2  = 1  # spo2_percent
FEAT_RR    = 2  # respiratory_rate (breaths/min)
FEAT_TEMP  = 3  # skin_temp_c
FEAT_SWEAT = 4  # sweat_rate_pct_per_min
FEAT_IMU   = 5  # imu_magnitude (m/s²)
FEAT_HRR   = 6  # hr_reserve_pct (0–100)

# ── Kotlin rule mirrors ───────────────────────────────────────────────────────

def label_vitals(hr, spo2, rr, temp) -> int:
    """Mirror VitalsRiskMonitor NEWS2 thresholds → 0=Low 1=Medium 2=High."""
    score = 0
    if hr >= 131 or hr <= 40:  score += 3
    elif hr >= 111 or hr <= 51: score += 1
    if spo2 <= 91:   score += 3
    elif spo2 <= 95: score += 1
    if rr >= 25 or rr <= 8:    score += 3
    elif rr >= 21 or rr <= 12: score += 1
    if temp >= 38.1 or temp <= 34.0:   score += 3
    elif temp >= 37.1 or temp <= 35.1: score += 1
    if score >= 3:   return 2
    elif score >= 2: return 1
    return 0


def label_dehydration(sweat, temp, hr) -> int:
    """Mirror DehydrationRiskModel → 0=Low 1=Medium 2=High."""
    sc = 0.0
    sc += 0.5 if sweat >= 1.5 else (0.25 if sweat >= 0.8 else 0)
    sc += 0.3 if temp >= 37.5 else (0.15 if temp >= 36.8 else 0)
    sc += 0.2 if hr >= 100 else (0.10 if hr >= 90 else 0)
    if sc >= 0.7:   return 2
    elif sc >= 0.4: return 1
    return 0


def label_overexertion(hr, spo2, rr, imu, age=70) -> int:
    """Mirror OverexertionModel (Tanaka HRmax) → 0=Safe 1=Caution 2=Stop."""
    hr_max = int(208 - 0.7 * age)
    hr_rest = 70
    reserve_range = max(hr_max - hr_rest, 1)
    hrr = min(max((hr - hr_rest) / reserve_range * 100, 0), 100)
    imu_dev = abs(imu - 9.81)

    sc = 0.0
    sc += 0.45 if hrr >= 75 else (0.25 if hrr >= 50 else (0.10 if hrr >= 25 else 0))
    spo2_drop = 97 - spo2
    sc += 0.25 if spo2_drop >= 3.5 else (0.12 if spo2_drop >= 2.5 else 0)
    sc += 0.15 if rr >= 22 else 0
    sc += 0.15 if imu_dev >= 6 else (0.08 if imu_dev >= 3 else 0)

    if sc >= 0.65:   return 2
    elif sc >= 0.30: return 1
    return 0


# ── Synthetic data generation ─────────────────────────────────────────────────

def generate_data(n: int, seed: int = RANDOM_SEED) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    rng = np.random.default_rng(seed)

    hr    = rng.uniform(35, 160, n).astype(np.float32)
    spo2  = rng.uniform(82, 100, n).astype(np.float32)
    rr    = rng.uniform(5, 30,  n).astype(np.float32)
    temp  = rng.uniform(33, 40, n).astype(np.float32)
    sweat = rng.uniform(0, 3,   n).astype(np.float32)
    imu   = rng.uniform(0, 25,  n).astype(np.float32)
    hrr   = rng.uniform(0, 100, n).astype(np.float32)

    X = np.stack([hr, spo2, rr, temp, sweat, imu, hrr], axis=1)

    y_vitals = np.array([label_vitals(hr[i], spo2[i], rr[i], temp[i]) for i in range(n)])
    y_dehyd  = np.array([label_dehydration(sweat[i], temp[i], hr[i])   for i in range(n)])
    y_over   = np.array([label_overexertion(hr[i], spo2[i], rr[i], imu[i]) for i in range(n)])

    return X, y_vitals.astype(np.int64), y_dehyd.astype(np.int64), y_over.astype(np.int64)


# ── Training ──────────────────────────────────────────────────────────────────

def train(args):
    os.makedirs(args.out, exist_ok=True)
    torch.manual_seed(RANDOM_SEED)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    print(f"Generating {args.samples:,} synthetic samples...")
    X, y_v, y_d, y_o = generate_data(args.samples)

    # Fit scaler on train portion, save for Android normalisation reference
    split = int(len(X) * 0.85)
    scaler = StandardScaler()
    X[:split] = scaler.fit_transform(X[:split])
    X[split:]  = scaler.transform(X[split:])
    joblib.dump(scaler, os.path.join(args.out, "health_risk_scaler.pkl"))

    # Tensors
    Xt = torch.FloatTensor(X)
    yvt = torch.LongTensor(y_v)
    ydt = torch.LongTensor(y_d)
    yot = torch.LongTensor(y_o)

    train_ds = TensorDataset(Xt[:split], yvt[:split], ydt[:split], yot[:split])
    test_ds  = TensorDataset(Xt[split:], yvt[split:], ydt[split:], yot[split:])
    train_dl = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True)

    model = HealthRiskMLP().to(device)
    opt   = torch.optim.Adam(model.parameters(), lr=args.lr)
    sched = torch.optim.lr_scheduler.ReduceLROnPlateau(opt, patience=5, factor=0.5)
    ce    = nn.CrossEntropyLoss()

    best_loss = float("inf")
    for epoch in range(args.epochs):
        model.train()
        total_loss = 0.0
        for Xb, yv, yd, yo in train_dl:
            Xb, yv, yd, yo = Xb.to(device), yv.to(device), yd.to(device), yo.to(device)
            out = model(Xb)
            loss = ce(out["vitals"], yv) + ce(out["dehydration"], yd) + ce(out["overexertion"], yo)
            opt.zero_grad(); loss.backward(); opt.step()
            total_loss += loss.item()
        avg = total_loss / len(train_dl)
        sched.step(avg)
        if avg < best_loss:
            best_loss = avg
            torch.save(model.state_dict(), os.path.join(args.out, "health_risk.pth"))
        if (epoch + 1) % 10 == 0:
            print(f"Epoch {epoch+1:3d}/{args.epochs}  loss={avg:.4f}  best={best_loss:.4f}")

    # Evaluate
    model.load_state_dict(torch.load(os.path.join(args.out, "health_risk.pth"), weights_only=True))
    model.eval()
    Xtest = test_ds.tensors[0].to(device)
    with torch.no_grad():
        out = model(Xtest)
    pv = out["vitals"].argmax(1).cpu().numpy()
    pd = out["dehydration"].argmax(1).cpu().numpy()
    po = out["overexertion"].argmax(1).cpu().numpy()

    print("\n=== Vitals Risk ===")
    print(classification_report(y_v[split:], pv, target_names=["Low","Medium","High"], zero_division=0))
    print("=== Dehydration ===")
    print(classification_report(y_d[split:], pd, target_names=["Low","Medium","High"], zero_division=0))
    print("=== Overexertion ===")
    print(classification_report(y_o[split:], po, target_names=["Safe","Caution","Stop"], zero_division=0))

    # Export TFLite
    _export_tflite(model, args.out, device)


def _export_tflite(model: HealthRiskMLP, out_dir: str, device):
    from config import HR_RISK_INPUT_DIM
    model.eval()
    onnx_path   = os.path.join(out_dir, "health_risk.onnx")
    tflite_path = os.path.join(out_dir, "health_risk.tflite")

    dummy = torch.randn(1, HR_RISK_INPUT_DIM).to(device)

    # Wrap forward_flat so TFLite gets a single output tensor (1, 9)
    class FlatModel(torch.nn.Module):
        def __init__(self, m): super().__init__(); self.m = m
        def forward(self, x): return self.m.forward_flat(x)

    flat = FlatModel(model)
    torch.onnx.export(
        flat, dummy, onnx_path,
        input_names=["input"], output_names=["output"],
        dynamic_axes={"input": {0: "batch"}, "output": {0: "batch"}},
        opset_version=17,
    )
    print(f"Exported ONNX: {onnx_path}")

    # Convert via onnx2tf (preferred) or tf
    converted = False
    try:
        import onnx2tf
        onnx2tf.convert(
            input_onnx_file_path=onnx_path,
            output_folder_path=out_dir,
            output_integer_quantized_tflite=False,
            verbosity="error",
        )
        candidate = os.path.join(out_dir, "health_risk_float32.tflite")
        if os.path.exists(candidate):
            os.rename(candidate, tflite_path)
            converted = True
    except ImportError:
        pass

    if not converted:
        try:
            import tensorflow as tf
            import onnx
            import onnx_tf
            onnx_model = onnx.load(onnx_path)
            tf_dir = os.path.join(out_dir, "health_risk_tf")
            onnx_tf.backend.prepare(onnx_model).export_graph(tf_dir)
            tfl = tf.lite.TFLiteConverter.from_saved_model(tf_dir).convert()
            with open(tflite_path, "wb") as f:
                f.write(tfl)
            converted = True
        except ImportError:
            pass

    if converted:
        kb = os.path.getsize(tflite_path) / 1024
        print(f"TFLite model: {tflite_path} ({kb:.1f} KB)")
        # Copy to Android assets
        android_dst = os.path.join(
            os.path.dirname(__file__),
            "../apps/android/app/src/main/assets/health_risk.tflite",
        )
        import shutil
        shutil.copy(tflite_path, android_dst)
        print(f"Copied to Android assets: {android_dst}")
    else:
        print(f"ONNX saved to {onnx_path} — install onnx2tf or onnx-tf to finish TFLite conversion.")
        print("  pip install onnx2tf  OR  pip install onnx-tf tensorflow")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--out",      default="models/")
    p.add_argument("--samples",  type=int,   default=HR_RISK_SYNTHETIC_SAMPLES)
    p.add_argument("--epochs",   type=int,   default=HR_RISK_EPOCHS)
    p.add_argument("--batch-size", type=int, default=HR_RISK_BATCH_SIZE)
    p.add_argument("--lr",       type=float, default=HR_RISK_LR)
    args = p.parse_args()
    train(args)
